### ISSUE TITLE
How to write an EXIF file in a webp

### ISSUE THREAD

**Issue by GladistonXD** [ApeironTsuka/node-webpmux#9]
`webpmux -set exif image_metadata.exif in.webp -o exif_container.webp`

I would like to use exactly this command only for node

I tried something like:
```
let img = new WebP.Image()

await img.load('in.webp')

img.exif = 'mage_metadata.exif'

await img.save('exif_container.webp')

```
I did not succeed

**Comment by ApeironTsuka** [comment]
The `.exif` property, along with the other metadata properties (`.xmp` and `.iccp`) are the raw data. You would instead do something like
```
const WebP = require('node-webpmux'), fs = require('fs/promises')
let img = new WebP.Image();
await img.load('in.webp');
img.exif = await fs.readFile('image_metadata.exif');
await img.save('exif_container.webp');
```
assigning the contents of the `image_metadata.exif` file directly rather than the filename. I'll update the README to clarify this after I think of a good way to word it.

**Comment by GladistonXD** [comment]
Now it worked perfectly, thank you very much :)
